### ISSUE TITLE
mac find:duplicated not working

### ISSUE THREAD

**Issue by berndblume** [guarinogabriel/mac-cli#16]
Just installed it and checked it out:
```
bb@broom:mac-cli/mac-cli % mac find:duplicated
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
uniq: illegal option -- w
usage: uniq [-c | -d | -u] [-i] [-f fields] [-s chars] [input [output]]
bb@broom:mac-cli/mac-cli % 
```

**Comment by guarinogabriel** [comment]
@berndblume Thanks for reporting that issue. I will get that fixed on the project.

**Comment by guarinogabriel** [comment]
@berndblume The issue has been fixed. Thanks for reporting that!

Commit: https://github.com/guarinogabriel/mac-cli/commit/7c80fa1dfe26857275f1e268d7f4d6ea758d175a

**Comment by berndblume** [comment]
I issued a `mac install:all` to update mac-cli. Still got the same error.
Then I did `mac update`. Took an eternity, some native ruby gem extensions (like json) could not be built because they refer to gcc.
After that, still the same error with `mac find:duplicated`.
